import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ".././globals.css";
import { Suspense } from "react";
import Skeleton from "@/components/Skeleton";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "bhade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen`}>
        <Suspense fallback={<Skeleton/>}>
         <Navbar/>
         <section className="flex absolute top-16 left-0">
          <Sidebar />
         <main className='md:ml-[200px] ml-0 p-4 w-screen md:w-[calc(100vw-200px)] bg-gray-50'>
         {children}
         </main>
         </section>
        </Suspense>
        </body>
    </html>
  );
}
